# Generated by Django 4.2.27 on 2026-01-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date d'enregistrement")),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('type_materiel', models.CharField(choices=[('informatique', 'Informatique'), ('mobilier', 'Mobilier'), ('vehicule', 'Véhicule'), ('outillage', 'Outillage'), ('telephonie', 'Téléphonie'), ('autre', 'Autre')], max_length=50, verbose_name='Type de matériel')),
                ('type_affectation', models.CharField(choices=[('permanent', 'Permanent'), ('temporaire', 'Temporaire'), ('pret', 'Prêt'), ('stock', 'Stock')], max_length=50, verbose_name="Type d'affectation")),
                ('emplacement', models.CharField(max_length=100, verbose_name='Emplacement')),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('bon', 'Bon état'), ('usage', 'Usé'), ('panne', 'En panne'), ('reforme', 'Réformé')], max_length=20, verbose_name='État')),
                ('stock', models.IntegerField(default=1, verbose_name='Quantité en stock')),
                ('fournisseur', models.CharField(max_length=100, verbose_name='Fournisseur')),
                ('date_reception', models.DateField(verbose_name='Date de réception')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('service_affecte', models.CharField(max_length=100, verbose_name='Service affecté')),
                ('utilisateur_affecte', models.CharField(max_length=100, verbose_name='Utilisateur affecté')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['-created_at'],
            },
        ),
    ]
