# Generated by Django 4.2.27 on 2026-01-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='date_prochaine_visite',
            field=models.DateField(blank=True, help_text='Date de la prochaine inspection/visite', null=True, verbose_name='Prochaine visite'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='defaut_panne',
            field=models.CharField(blank=True, choices=[('defaut', 'Défaut'), ('panne', 'Panne')], help_text='Type de problème constaté', max_length=10, verbose_name='Défaut/Panne'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='kilometrage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indiquez le kilométrage actuel', max_digits=10, null=True, verbose_name='Kilométrage'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='numero_vehicule',
            field=models.CharField(blank=True, help_text="Numéro d'immatriculation ou identifiant", max_length=50, verbose_name='Numéro véhicule'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat ou de réparation", max_digits=10, null=True, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='reference_piece',
            field=models.CharField(blank=True, help_text='Référence des pièces de rechange', max_length=100, verbose_name='Référence pièce'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='reparation',
            field=models.TextField(blank=True, help_text='Description des réparations effectuées', verbose_name='Réparation'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='type_vehicule',
            field=models.CharField(blank=True, choices=[('voiture', 'Voiture'), ('camion', 'Camion'), ('moto', 'Moto'), ('utilitaire', 'Utilitaire'), ('engin', 'Engin de chantier'), ('autre', 'Autre')], help_text='Type de véhicule si applicable', max_length=20, verbose_name='Type véhicule'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='observation',
            field=models.CharField(choices=[('marche', 'Marche'), ('arret', 'Arrêt'), ('en_cours', 'En cours')], default='marche', max_length=20, verbose_name='Observation'),
        ),
    ]
