# Generated by Django 6.0.1 on 2026-02-10 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0004_rename_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='date_entree',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='date_sortie',
            field=models.DateField(blank=True, null=True, verbose_name='Date de sortie'),
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField(verbose_name='Date de visite')),
                ('type_visite', models.CharField(choices=[('entretien', 'Entretien'), ('controle_technique', 'Contrôle Technique'), ('inspection', 'Inspection'), ('reparation', 'Réparation'), ('prevention', 'Visite Préventive'), ('autre', 'Autre')], max_length=20, verbose_name='Type de visite')),
                ('kilometrage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilométrage')),
                ('responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable/Mécanicien')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût')),
                ('prochaine_visite', models.DateField(blank=True, null=True, verbose_name='Prochaine visite prévue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='materiel.materiel')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-date_visite'],
            },
        ),
        migrations.CreateModel(
            name='ControleVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_controle', models.CharField(choices=[('huile_moteur', 'Huile moteur'), ('filtres', 'Filtres'), ('freins', 'Freins'), ('pneus', 'Pneus'), ('batterie', 'Batterie'), ('systeme_electronique', 'Système électronique'), ('climatisation', 'Climatisation'), ('suspension', 'Suspension'), ('echappement', 'Échappement'), ('transmission', 'Transmission'), ('eclairage', 'Éclairage'), ('autre', 'Autre')], max_length=30, verbose_name='Type de contrôle')),
                ('effectue', models.BooleanField(default=True, verbose_name='Contrôle effectué')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Détails du contrôle')),
                ('pieces_changees', models.TextField(blank=True, null=True, verbose_name='Pièces changées')),
                ('visite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='materiel.visite')),
            ],
            options={
                'verbose_name': 'Contrôle de visite',
                'verbose_name_plural': 'Contrôles de visite',
            },
        ),
    ]
